//! Device identity and recovery policy for providers that report device sets to Bevy.

mod apply;
mod attempt;
mod binding;
mod capabilities;
mod claim;
mod contract;
mod devices;
mod discovery;
mod emit;
mod endpoint;
mod events;
mod evidence;
mod fault;
mod identity;
mod identity_decisions;
mod limits;
mod plugin;
mod policy;
mod presence;
mod reconcile;
mod recovery;
mod registration;
mod role;
mod scheme;
mod verdict;

pub use attempt::Attempt;
pub use attempt::AttemptId;
pub use attempt::AttemptInvalidation;
pub use attempt::AttemptOutcome;
pub use attempt::AttemptProgress;
pub use attempt::LastAttemptEnding;
pub use attempt::LastKnownGoodConfiguration;
pub use binding::ApplyDeadline;
pub use binding::AvailableConfiguration;
pub use binding::Binding;
pub use binding::BindingCapacityError;
pub use binding::BindingEntities;
pub use binding::BindingEntityLookup;
pub use binding::BindingError;
pub use binding::BindingGeneration;
pub use binding::Bindings;
pub use binding::ConfiguredDevice;
pub use binding::ConfiguredDeviceConnection;
pub use binding::ConfiguredDeviceMode;
pub use binding::HardwareInventory;
pub use binding::HardwareInventoryError;
pub use binding::ReadyRole;
pub use binding::RequestedConfiguration;
pub use binding::ResolvedBindings;
pub use binding::ResolvedToDevice;
pub use binding::RetirementOutcome;
pub use binding::StartApplyRequest;
pub use binding::WaitingWork;
pub use capabilities::Capabilities;
pub use claim::Claim;
pub use claim::ClaimHolder;
pub use claim::PermissionGate;
pub use contract::CaptureOutcome;
pub use contract::DeviceReporter;
pub use contract::DiscoveryJob;
pub use contract::DiscoveryProgress;
pub use contract::DiscoveryProgressSendError;
pub use contract::DiscoveryProgressSender;
pub use contract::DiscoveryWork;
pub use contract::DriverContractError;
pub use contract::EndpointDriver;
pub use contract::MainThreadDiscoveryJob;
pub use devices::ApplyAuthorizationError;
pub use devices::AttemptLookup;
pub use devices::Attempts;
pub use devices::Device;
pub use devices::DeviceDeparture;
pub use devices::DeviceResolution;
pub use devices::DeviceRevision;
pub use devices::DeviceRevisionLookup;
pub use devices::DeviceStateLookup;
pub use devices::Devices;
pub use devices::ReconciledDeviceState;
pub use devices::RiggingRevision;
pub use discovery::AuthoritativeReporterCoverage;
pub use discovery::CompletedDiscoveryOutcome;
pub use discovery::CoveredDeviceIdentitySpace;
pub use discovery::DiscoveryBatchId;
pub use discovery::DiscoveryCadence;
pub use discovery::DiscoveryControl;
pub use discovery::DiscoveryControlError;
pub use discovery::DiscoveryLimits;
pub use discovery::DiscoverySchedulerError;
pub use discovery::DiscoverySchedulerState;
pub use discovery::DiscoveryStatus;
pub use discovery::DiscoveryStatusError;
pub use discovery::LastDiscoveryOutcome;
pub use discovery::ReporterActivation;
pub use discovery::ReporterActivity;
pub use discovery::ReporterCoverage;
pub use discovery::ReporterDiscoveryStatus;
pub use discovery::ReporterRegistration;
pub use discovery::StartupDiscoveryState;
pub use endpoint::DeviceEndpoint;
pub use endpoint::EndpointId;
pub use endpoint::PartName;
pub use endpoint::PartNameError;
pub use events::AttemptFinished;
pub use events::BindingRetired;
pub use events::CapabilitiesDisputed;
pub use events::ClaimChanged;
pub use events::ConfiguredDeviceConnectionChanged;
pub use events::DeviceArrived;
pub use events::DeviceDeparted;
pub use events::DiscoveryFinished;
pub use events::DiscoveryProgressChanged;
pub use events::IdentityChanged;
pub use events::IdentityQuestionExpired;
pub use events::IdentityQuestionRaised;
pub use events::PresenceChanged;
pub use events::ReapplyConfiguration;
pub use events::RecoveryPolicyChanged;
pub use events::RetireRole;
pub use events::RetiredRoleAttemptEnded;
pub use events::RoleAvailable;
pub use events::RoleAwaiting;
pub use events::RoleStateChanged;
pub use events::SessionLossDisposition;
pub use events::SessionLossProcessed;
pub use events::SessionLossRefusal;
pub use events::SessionLossReport;
pub use events::SessionLossReports;
pub use events::StartupDiscoveryChanged;
pub use events::UnregisteredSchemeReported;
pub use evidence::AttachmentPath;
pub use evidence::DeviceDescriptor;
pub use evidence::PlatformDeviceHandle;
pub use fault::DeviceAccessError;
pub use identity::DeviceId;
pub use identity::DeviceIdSource;
pub use identity::DeviceKey;
pub use identity::DeviceKind;
pub use identity_decisions::AdoptionOutcome;
pub use identity_decisions::IdentityAdoptionPreparation;
pub use identity_decisions::IdentityAnswer;
pub use identity_decisions::IdentityDecisions;
pub use identity_decisions::IdentityQuestion;
pub use identity_decisions::IdentityQuestionLookup;
pub use identity_decisions::IdentityQuestionState;
pub use identity_decisions::PreparedIdentityAdoption;
pub use limits::RiggingLimits;
pub use plugin::RiggingPlugin;
pub use plugin::RiggingSystems;
pub use policy::OnAbort;
pub use policy::OnSessionLoss;
pub use policy::RetryOn;
pub use presence::DeviceRecord;
pub use presence::DeviceScan;
pub use presence::Presence;
pub use presence::ReportAcceptanceProjection;
pub use presence::ReportedAs;
pub use presence::ReportedParent;
pub use presence::ReporterId;
pub use recovery::RecoveryPolicy;
pub use registration::ApplyPermit;
pub use registration::DriverId;
pub use registration::Drivers;
pub use registration::RiggingAppExt;
pub use role::RoleKey;
pub use role::RoleKeyError;
pub use role::RoleState;
pub use scheme::AuthoredId;
pub use scheme::AuthoredIdError;
pub use scheme::Digest;
pub use scheme::RegisteredSchemes;
pub use scheme::ReportedId;
pub use scheme::ReportedIdError;
pub use scheme::SchemeName;
pub use scheme::SchemeNameError;
pub use scheme::UnregisteredSchemeError;
pub use verdict::IdentityDecisionOwed;
pub use verdict::IdentityVerdict;
pub use verdict::ReportedSerial;
pub use verdict::UnverifiedReason;

/// Common types for reporting devices to the kernel and for reading the identity verdicts it
/// returns.
pub mod prelude {
    pub use crate::AdoptionOutcome;
    pub use crate::ApplyAuthorizationError;
    pub use crate::ApplyDeadline;
    pub use crate::ApplyPermit;
    pub use crate::AttachmentPath;
    pub use crate::Attempt;
    pub use crate::AttemptFinished;
    pub use crate::AttemptId;
    pub use crate::AttemptLookup;
    pub use crate::AttemptOutcome;
    pub use crate::AttemptProgress;
    pub use crate::Attempts;
    pub use crate::AuthoredId;
    pub use crate::AuthoritativeReporterCoverage;
    pub use crate::AvailableConfiguration;
    pub use crate::Binding;
    pub use crate::BindingEntities;
    pub use crate::BindingEntityLookup;
    pub use crate::BindingError;
    pub use crate::BindingRetired;
    pub use crate::Bindings;
    pub use crate::Capabilities;
    pub use crate::CapabilitiesDisputed;
    pub use crate::CaptureOutcome;
    pub use crate::Claim;
    pub use crate::ClaimChanged;
    pub use crate::ClaimHolder;
    pub use crate::CompletedDiscoveryOutcome;
    pub use crate::ConfiguredDevice;
    pub use crate::ConfiguredDeviceConnection;
    pub use crate::ConfiguredDeviceConnectionChanged;
    pub use crate::ConfiguredDeviceMode;
    pub use crate::CoveredDeviceIdentitySpace;
    pub use crate::DeviceAccessError;
    pub use crate::DeviceArrived;
    pub use crate::DeviceDeparted;
    pub use crate::DeviceDeparture;
    pub use crate::DeviceDescriptor;
    pub use crate::DeviceEndpoint;
    pub use crate::DeviceId;
    pub use crate::DeviceIdSource;
    pub use crate::DeviceKey;
    pub use crate::DeviceKind;
    pub use crate::DeviceRecord;
    pub use crate::DeviceReporter;
    pub use crate::DeviceResolution;
    pub use crate::DeviceRevision;
    pub use crate::DeviceRevisionLookup;
    pub use crate::DeviceScan;
    pub use crate::DeviceStateLookup;
    pub use crate::Devices;
    pub use crate::Digest;
    pub use crate::DiscoveryBatchId;
    pub use crate::DiscoveryCadence;
    pub use crate::DiscoveryControl;
    pub use crate::DiscoveryFinished;
    pub use crate::DiscoveryJob;
    pub use crate::DiscoveryLimits;
    pub use crate::DiscoveryProgress;
    pub use crate::DiscoveryProgressChanged;
    pub use crate::DiscoveryStatus;
    pub use crate::DiscoveryWork;
    pub use crate::DriverId;
    pub use crate::Drivers;
    pub use crate::EndpointDriver;
    pub use crate::EndpointId;
    pub use crate::HardwareInventory;
    pub use crate::IdentityAdoptionPreparation;
    pub use crate::IdentityAnswer;
    pub use crate::IdentityChanged;
    pub use crate::IdentityDecisionOwed;
    pub use crate::IdentityDecisions;
    pub use crate::IdentityQuestion;
    pub use crate::IdentityQuestionExpired;
    pub use crate::IdentityQuestionLookup;
    pub use crate::IdentityQuestionRaised;
    pub use crate::IdentityQuestionState;
    pub use crate::IdentityVerdict;
    pub use crate::LastDiscoveryOutcome;
    pub use crate::LastKnownGoodConfiguration;
    pub use crate::MainThreadDiscoveryJob;
    pub use crate::OnAbort;
    pub use crate::OnSessionLoss;
    pub use crate::PartName;
    pub use crate::PartNameError;
    pub use crate::PlatformDeviceHandle;
    pub use crate::PreparedIdentityAdoption;
    pub use crate::Presence;
    pub use crate::PresenceChanged;
    pub use crate::ReapplyConfiguration;
    pub use crate::RecoveryPolicy;
    pub use crate::RecoveryPolicyChanged;
    pub use crate::RegisteredSchemes;
    pub use crate::ReportAcceptanceProjection;
    pub use crate::ReportedAs;
    pub use crate::ReportedId;
    pub use crate::ReportedParent;
    pub use crate::ReportedSerial;
    pub use crate::ReporterActivation;
    pub use crate::ReporterActivity;
    pub use crate::ReporterCoverage;
    pub use crate::ReporterDiscoveryStatus;
    pub use crate::ReporterId;
    pub use crate::ReporterRegistration;
    pub use crate::RequestedConfiguration;
    pub use crate::ResolvedBindings;
    pub use crate::ResolvedToDevice;
    pub use crate::RetireRole;
    pub use crate::RetiredRoleAttemptEnded;
    pub use crate::RetirementOutcome;
    pub use crate::RetryOn;
    pub use crate::RiggingAppExt;
    pub use crate::RiggingLimits;
    pub use crate::RiggingPlugin;
    pub use crate::RiggingRevision;
    pub use crate::RiggingSystems;
    pub use crate::RoleAvailable;
    pub use crate::RoleAwaiting;
    pub use crate::RoleKey;
    pub use crate::RoleKeyError;
    pub use crate::RoleState;
    pub use crate::RoleStateChanged;
    pub use crate::SchemeName;
    pub use crate::SchemeNameError;
    pub use crate::SessionLossDisposition;
    pub use crate::SessionLossProcessed;
    pub use crate::SessionLossRefusal;
    pub use crate::SessionLossReport;
    pub use crate::SessionLossReports;
    pub use crate::StartupDiscoveryChanged;
    pub use crate::StartupDiscoveryState;
    pub use crate::UnregisteredSchemeError;
    pub use crate::UnregisteredSchemeReported;
    pub use crate::UnverifiedReason;
}
