//! Runtime-generated schema and reference metadata for keymap documents.

use serde_json_lenient::Error;
use serde_json_lenient::Map;
use serde_json_lenient::Value;

use crate::Capability;
use crate::CommandRegistry;
use crate::Keystroke;
use crate::condition::StateDimensionRegistry;

/// Serializes the schema generated from the command and state-dimension registries.
pub(crate) fn state_dimension_schema_bytes(
    command_registry: &CommandRegistry,
    state_dimensions: &StateDimensionRegistry,
) -> Result<Vec<u8>, Error> {
    serde_json_lenient::to_vec_pretty(&state_dimension_schema_document(
        command_registry,
        state_dimensions,
    ))
}

/// Prepends state-dimension reference comments to embedded defaults.
pub(crate) fn state_dimension_reference_default_bytes(
    defaults: &str,
    state_dimensions: &StateDimensionRegistry,
    protected_keystrokes: &[Keystroke],
) -> Vec<u8> {
    let mut header = String::from("// Keymap reference\n");
    if protected_keystrokes.is_empty() {
        header.push_str("// Protected recovery keystrokes: none.\n");
    } else {
        for protected_keystroke in protected_keystrokes {
            header.push_str("// Protected recovery keystroke: ");
            push_comment_text(&mut header, &protected_keystroke.to_string());
            header.push_str(".\n");
        }
    }
    let dimensions = state_dimensions.metadata();
    if dimensions.is_empty() {
        header.push_str("// Context vocabulary: global blocks only.\n");
    } else {
        for dimension in dimensions {
            header.push_str("// State dimension `");
            header.push_str(dimension.name.as_str());
            header.push_str("`: ");
            push_comment_text(&mut header, dimension.description);
            header.push('\n');
            for value in dimension.values {
                header.push_str("//   `");
                header.push_str(value.name.as_str());
                header.push_str("`: ");
                push_comment_text(&mut header, value.description);
                header.push('\n');
            }
        }
    }
    header.push('\n');

    let mut bytes = header.into_bytes();
    bytes.extend_from_slice(defaults.as_bytes());
    bytes
}

fn push_comment_text(header: &mut String, text: &str) {
    let mut lines = text.split('\n');
    if let Some(first_line) = lines.next() {
        header.push_str(first_line);
    }
    for line in lines {
        header.push_str("\n// ");
        header.push_str(line);
    }
}

fn state_dimension_schema_document(
    command_registry: &CommandRegistry,
    state_dimensions: &StateDimensionRegistry,
) -> Value {
    let binding_value_schema = binding_value_schema(command_alternatives(command_registry));
    let context_schema = state_dimension_context_schema(state_dimensions);
    let block_schema = block_schema(binding_value_schema, context_schema);

    serde_json_lenient::json!({
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "Hana keymap",
        "description": "Generated by hana_rubric at application startup. This file is overwritten on the next launch.",
        "type": "object",
        "properties": {
            "$schema": {
                "type": "string",
                "description": "Relative path to the generated Hana keymap schema."
            },
            "bindings": {
                "type": "array",
                "description": "Ordered keymap blocks. Later matching blocks override earlier bindings.",
                "items": block_schema
            }
        },
        "required": ["bindings"],
        "additionalProperties": false
    })
}

fn command_alternatives(command_registry: &CommandRegistry) -> Vec<Value> {
    command_registry
        .iter()
        .filter(|command| command.capability.is_user_bindable())
        .map(|command| {
            let description = command_description(command.description, command.capability);

            serde_json_lenient::json!({
                "type": "string",
                "const": command.id.as_str(),
                "description": description
            })
        })
        .collect()
}

fn command_description(description: &str, capability: Capability) -> String {
    if capability == Capability::Held {
        format!(
            "{description} A held command can be bound to one keystroke only, not a multi-key sequence."
        )
    } else {
        description.to_owned()
    }
}

fn binding_value_schema(command_alternatives: Vec<Value>) -> Value {
    let mut alternatives = command_alternatives;
    alternatives.push(serde_json_lenient::json!({
        "type": "null",
        "description": "Removes the binding at this key and context identity. The key is inert here rather than inherited from an earlier block."
    }));

    serde_json_lenient::json!({ "anyOf": alternatives })
}

fn state_dimension_context_schema(state_dimensions: &StateDimensionRegistry) -> Value {
    let dimensions = state_dimensions.metadata();
    if dimensions.is_empty() {
        return serde_json_lenient::json!({
            "description": "This application accepts global keymap blocks only.",
            "not": {}
        });
    }

    let mut properties = Map::new();
    for dimension in dimensions {
        let alternatives = dimension
            .values
            .iter()
            .map(|value| {
                serde_json_lenient::json!({
                    "type": "string",
                    "const": value.name.as_str(),
                    "description": value.description,
                })
            })
            .collect::<Vec<_>>();
        properties.insert(
            dimension.name.as_str().to_owned(),
            serde_json_lenient::json!({
                "description": dimension.description,
                "anyOf": alternatives,
            }),
        );
    }

    serde_json_lenient::json!({
        "type": "object",
        "description": "A conjunction of registered application state dimensions.",
        "properties": properties,
        "additionalProperties": false,
        "minProperties": 1,
    })
}

fn block_schema(binding_value_schema: Value, context_schema: Value) -> Value {
    let mut properties = Map::new();
    properties.insert(
        "bindings".to_owned(),
        serde_json_lenient::json!({
            "type": "object",
            "description": "Maps a keystroke sequence to a command or null tombstone.",
            "propertyNames": {
                "type": "string",
                "description": "A Hana keystroke sequence. Modifiers before an ordinary key form a chord. A bare shift, ctrl, alt, or secondary modifier family is valid only as the sole keystroke bound to a held command."
            },
            "additionalProperties": binding_value_schema
        }),
    );
    properties.insert("context".to_owned(), context_schema);

    serde_json_lenient::json!({
        "type": "object",
        "properties": properties,
        "required": ["bindings"],
        "additionalProperties": false
    })
}
